download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","power.zip",method="curl")
unzip("power.zip")

db<-read.table("household_power_consumption.txt",header = FALSE,sep = ";",na.strings = "?",skip = 66637,nrows = 2880)
names(db) <- read.table("household_power_consumption.txt",sep=";",nrows = 1)
library(dplyr)
library(lubridate)
dbTime <- mutate(db,datetime=dmy_hms(paste(Date,Time)))

png(filename = "plot3.png", width = 480, height = 480)
with(dbTime, plot(datetime,Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering"))
lines(dbTime$datetime,dbTime$Sub_metering_2, col="red")
lines(dbTime$datetime,dbTime$Sub_metering_3, col="blue")
legend(x = "topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = c(1,1,1))
dev.off()
